-- Payment Transactions table (reference only — Sequelize auto-creates via sync)
-- This file is kept for documentation purposes.
-- Do NOT run ALTER TABLE here — Sequelize sync({ alter: true }) handles it.
